# AppVeyor CI build file, https://ci.appveyor.com/project/odinserj/hangfire

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Please don't edit it manually, use the `build.bat version` command instead.
version: 0.4.4-build-0{build}

image: Visual Studio 2022

environment:
  SIGNPATH_API_TOKEN:
    secure: 0MMHWtCS0+XF5ow/I+UUpogfKHPt3iLqQCIDVbgYDzIjqXbQzRoCE2QEkX1omu1j

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - pwsh: Install-PSResource -Name SignPath -TrustRepository

# to run your custom scripts instead of automatic MSBuild
build_script: build.bat sign

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'build\**\*.nupkg'
  - path: 'build\**\*.zip'

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy:
  - provider: NuGet
    api_key: 
      secure: m7mcrRz5rnmbkoH0xA/Y7A2NF7XHsTvE1+v+I6X2oBEwaozK/QvsByMyzeEdCRQf
    on:
      appveyor_repo_tag: true
